services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  nest-app:
    build: .
    container_name: nest-app
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/nest-auth-db

volumes:
  mongo_data:
